adopted-ember-addons/ember-cli-flash

- README.md
- addon/components/flash-message.js
- addon/flash/object.js
- addon/services/flash-messages-service.js
- tests/acceptance/integration-test.js
- tests/dummy/app/routes/index.js
- tests/unit/flash/object-test.js
- added deprecation warning for `addMessage`
- reduced testTimerDuration
- added test for sticky messages
- added integration test for sticky messages
- fixed a bug where sometimes flash messages would not be removed
- can now add sticky messages
- updated readme
Closes #12
> Can now make flash messages sticky

- README.md
- addon/services/flash-messages-service.js
- index.js
- tests/dummy/config/environment.js
- tests/unit/services/flash-messages-service-test.js
Taken over from #29:
---
Here's the first pass, as discussed.
__TODO:__
Closes #6, partially address #9. Closes #29
> [WIP] Allow global service configuration

- README.md
- addon/components/flash-message.js
- addon/services/flash-messages-service.js
- app/templates/components/flash-message.hbs
- bower.json
- package.json
- tests/acceptance/integration-test.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/index.js
- tests/dummy/app/templates/application.hbs
- tests/unit/services/flash-messages-service-test.js
- skip some integration tests until a better way to test run.later
- updated integration test to use timeout val from config
- removed individual timeout override in dummy route
- escape css in component before binding to style attr
- update to new bind-attr-less syntax
- fixed use of classify string prototype
- updated bower and npm
- updated readme about compat (Closes #42)
- don't pass in literal values to the style attr
> Updated ember-cli to 0.2.2

- app/templates/components/flash-message.hbs
- bower.json
- config/ember-try.js
- index.js
- package.json
* Remove ember-data from build.  This library does not use ember-data, and occasionally having ember-data in the build causes test failures (ember-data 1.0.0-beta.16.1 does not work with Ember canary at this point).
* Test across many versions of Ember.
* Use ember-cli-babel instead of custom preprocessor.
* Fix style warning on 1.12.0-beta.1+.
> Minor build/test tweaks.

- addon/components/flash-message.js
- addon/flash/object.js
- addon/services/flash-messages-service.js
- tests/acceptance/integration-test.js
- tests/dummy/app/routes/index.js
- tests/dummy/config/environment.js
- tests/helpers/utils/lookup.js
- tests/unit/components/flash-message-test.js
- tests/unit/flash/object-test.js
- tests/unit/services/flash-messages-service-test.js
Addresses points from #44
- props that should be readOnly are now actually readOnly
- added tests for readOnly props in flash model
- stop using var in tests
- use Ember.EnumerableUtils instead of array prototype methods
- added tests for readOnly prop on service
- reorganised variable declarations in service test
- added tests for readOnly props on component
- fixed missing super
- fixed setting state on prototype
- fixed indentation issue in service
- removed redundant private method in flash model
- updated tests
- addded Evented mixin to flash object
- added lookup helpers in testing
- made default sticky in testing true
> Refactoring

- addon/components/flash-message.js
- addon/services/flash-messages-service.js
- app/initializers/flash-messages-service.js
- tests/unit/components/flash-message-test.js
Updated CPs now explicitly have a setter which returns if being set,
instead of using `ComputedPropertyPrototype.readOnly`
> Updated CP syntax.

- README.md
- addon/components/flash-message.js
- addon/flash/object.js
- addon/services/flash-messages-service.js
- config/environment.js
- tests/dummy/config/environment.js
- tests/unit/components/flash-message-test.js
- tests/unit/flash/object-test.js
My solution to fix #52
Setting disappearTimeout on a message (or in the config) will cause the class
‘disappearing’ to be added to the message after the timeout.  This
should allow for CSS animation to take place before the message element
is destroyed like:
```scss
.alert {
opacity: 1;
transition: all 2s linear;
&.disappearing {
opacity: 0;
}
}
```
I kicked around the names for the option *disappearTimeout* and the class *disappearing* with a few people around the office and this is the best we could come up with.  Other ideas would be welcome. 
The way you are using services, objects, and components here is foreign territory for me.  So there are areas where I :monkey: copied for sure.  I got some great help on the ember slack channel from *cody.mcculloch* and *davidpett*.  Thanks to …
> Added extendTimeout as a configuration option to make animation possible

- addon/components/flash-message.js
- tests/dummy/app/styles/app.css
- tests/dummy/config/environment.js
- tests/unit/components/flash-message-test.js
In order to make the CSS animation work properly, some style has to change after inserting the flash message into the DOM. Setting active to true doesn't have the desired effect, so (I think) progress bars have never worked.
> Add active class to flash messages upon DOM insertion

- README.md
- addon/flash/object.js
- addon/services/flash-messages-service.js
- addon/utils/computed.js
- circle.yml
- config/environment.js
- tests/dummy/config/environment.js
- tests/unit/services/flash-messages-service-test.js
- tests/unit/utils/computed-test.js
- Fixed an issue where default `type` was not being applied correctly
- Adds the ability to set a `preventDuplicates` default on the service to prevent duplicate messages (by `message`) from being added
- Reorganized README
> Adds the ability to prevent duplicate messages from being added

- app/initializers/flash-messages.js
This PR removes a [deprecation introduced in Ember 2.1](http://emberjs.com/deprecations/v2.x/#toc_initializer-arity).
> update to remove ember 2.1 deprecation

- README.md
Using a dynamic template for {{render}} appears to be deprecated. The component helper offers a nice alternative.
> Change {{render}} example to use component helper.

- package.json
This does not fix the issue reported in https://github.com/poteto/ember-cli-flash/issues/92, but if all consumers of ember-new-computed used SemVer allowed drifting versions we should be able to avoid issues of different deps clobbering others.
> Update ember-new-computed to allow a bit more flexibility.

- addon/services/flash-messages.js
- tests/unit/services/flash-messages-test.js
> Implement fluent API to support chaining

- addon/components/flash-message.js
- tests/unit/components/flash-message-test.js
Currently, the active class is added at the exact same time the message is
rendered (despite the afterRender queue). This will ensure that the active
class is added 1ms after it is inserted into the DOM, thus triggering any CSS
transitions from naked to active states.
> Add active class in run.next instead of afterRender queue

- addon/components/flash-message.js
- tests/integration/components/flash-message-test.js
I have a login route that renders flash messages in a certain part of the template. Then the primary parent route of the application renders flash messages again. I was getting a "cannot call set on destroyed object" from [this code](https://github.com/poteto/ember-cli-flash/blob/1.3.12/addon/components/flash-message.js#L53).
I added a component integration test to show the issue: after a component is torn down, `_setActive` still tries to change a property on that component. 
The simple fix is to check for `isDestroyed` on that component, but probably there is a more wholistic refactor needed.
> Fix calling set on destroyed object error

- addon/utils/computed.js
- tests/unit/utils/computed-test.js
Hello!
This PR allows using Ember i18n service, or any string which is an Ember SafeString and have the `{ preventDuplicates: true }` work by computing the guid value on the stringified version of the message. Before, it computed the guid directly, so two different instance of the same objet would get different guid. I added a test to cover the case.
Note: there is a test failing, but it was failing before too.
> Compute guid on .toString() version of the message.

- README.md
- addon/components/flash-message.js
- tests/unit/components/flash-message-test.js
This PR adds the following option:
- `destroyOnClick?: number`
Default: `true`
By default, flash messages will be destroyed on click.  Disabling this can be useful if the message supports user interaction.
> Add destroyOnClick option

- addon/services/flash-messages.js
- package.json
- tests/unit/utils/computed-test.js
Hi! Just a quick PR to knock out some usage that was deprecated in Ember 2.8.
In runtime code, there was one `Enumerable#contains` that I [changed to `includes`](http://emberjs.com/deprecations/v2.x/#toc_enumerable-contains) and added the polyfill for in order to maintain backwards compatibility. 
I also updated a couple instances of `Handlebars.SafeString` [to `String.htmlSafe`](http://emberjs.com/deprecations/v2.x/#toc_use-ember-string-htmlsafe-over-ember-handlebars-safestring) in test code since I was picking over test output for deprecation warnings anyway.
> Fix Ember 2.8 deprecations

- tests/unit/components/flash-message-test.js
Master was getting failures when trying to run `flash.destroy()` on unit level tests of our component:
`Assertion Failed: Cannot call writeDeps after the object is destroyed.`
> remove flash.destroy as it fails on latest builds of Ember

- README.md
Fixes: https://github.com/poteto/ember-cli-flash/issues/216
Our `assert.ok` will always pass in the example. Testing against `length` should work as demonstrated in this twiddle:
https://ember-twiddle.com/367f2485e4d8e6ceaa31c0a9932eb2e3?openFiles=tests.acceptance.my-acceptance-test.js%2C
> update acceptance test documentation for assertion

- README.md
- addon/services/flash-messages.js
- tests/unit/services/flash-messages-test.js
This should address the issue raised by #154.  A fluent API allows for chaining methods, but does not give access to the flash object. For users who want to manipulate the object directly, they can access it with the `getFlashObject` method, which will return the last object added to the queue.
> add chainable method for returning flash object

- addon/components/flash-message.js
- addon/flash/object.js
- addon/services/flash-messages.js
- addon/utils/computed.js
- package.json
If this addons is 1.12+ (and I think that it safe to assume it is), this
addon is not needed anymore.
> Remove unnecesary ember-new-computed addon

- CHANGELOG.md
- package.json
> version bump to 1.4.0

- addon/flash/object.js
- tests/unit/flash/object-test.js
Fixes: https://github.com/poteto/ember-cli-flash/issues/222
The method to defer our timers wasn't checking to see if that object was sticky.  This PR adds an early return to the timer methods and test to ensure they are not called.
> leave message on mouseover if sticky

- README.md
- addon/flash/object.js
- tests/unit/flash/object-test.js
This PR adds a callback function that can be passed in and called when a flash is destroyed.
Addresses: https://github.com/poteto/ember-cli-flash/issues/212
> Add onDestroy callback method for flash object destroy

- README.md
- addon/components/flash-message.js
- addon/templates/components/flash-message.hbs
- tests/integration/components/flash-message-test.js
This adds in the ability to close the flash message in your own custom components. I tweaked the example in the readme to include a close button in the template there. I've also tried this in my own app :)
If we like this idea, we should probably make a separate example that has close on click set to false (since currently this example it wouldn't quite make sense why we want the close button when you can click on the whole thing to close it).
> Pass 'close' as closure action

- addon/components/flash-message.js
- addon/flash/object.js
- tests/dummy/app/routes/index.js
- tests/dummy/app/styles/app.css
- tests/integration/components/flash-message-test.js
- tests/unit/flash/object-test.js
This removes the logic around pausing and restarting timers in favor of setting a flag which prevents the exit and destroy while being moused over. A related change is to set the timeout timer to trigger `exitMessage` which in turn sets a timer of destroy based on the `extendedTimout`. This prevents having to juggle two timers separately.
In reference to Issue [237](https://github.com/poteto/ember-cli-flash/issues/237)
> Prevent early destruction from mouse events

- .eslintrc.js
- .gitignore
- .npmignore
- addon/flash/object.js
- package.json
- testem.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/start-app.js
- tests/index.html
- tests/integration/components/flash-message-test.js
- tests/unit/components/flash-message-test.js
- yarn.lock
- Update to ember 2.15
- Remove some unused dependencies
- Move away from `sinon` for stubbing methods
- Update testem and remove jshint completely
closes: https://github.com/poteto/ember-cli-flash/issues/242
> upgrade to 2.15

- addon/components/flash-message.js
> Add base class 'flash-message' to flash component

- README.md
- addon/components/flash-message.js
- addon/flash/object.js
- package.json
- tests/acceptance/main-test.js
- tests/dummy/app/routes/index.js
- tests/integration/components/flash-message-test.js
- tests/unit/components/flash-message-test.js
- tests/unit/flash/object-test.js
- yarn.lock
This reverts commit eec395792e2941e552f93f2ab358d30bf0e40812.
This causes problems because `ember-concurrency` is not in this addon's dependecies.  I'm reverting so we can have a little more discussion about this without having 1.6 out there broken.
> Revert "extendTimeout on sticky message (#240)"

- index.d.ts
- package.json
- yarn.lock
Fixes #257 
Consumers will need to do the following in order to take advantage of this type information.
```ts
import Component from '@ember/component';
import ComputedProperty from '@ember/object/computed';
import { inject } from '@ember/service';
import FlashService from 'ember-cli-flash/services/flash-messages';
export default class XFooComponent extends Component {
public flashMessages: ComputedProperty<FlashService> = inject();
public onSuccess() {
// Type-check is happy with this!
this.get('flashMessages').success('Success!');
}
}
```
> Add ambient TypeScript type information

- README.md
- addon/services/flash-messages.js
- tests/unit/services/flash-messages-test.js
fixes #259 
I figured it would be reasonable to keep the `message` property required when `preventDuplicates` is enabled as that feature relies on the message string.
Please let me know or feel free to modify the added test, if you know of any better way to assert a thrown error than that:
```
assert.throws((() => {
service.add({ });
}).message, 'Assertion Failed: The flash message cannot be empty when preventDuplicates is enabled.');
```
> remove requirement for providing a message

- blueprints/ember-cli-flash/index.js
- package.json
On newer Ember versions, test-helper.js does not include an `import { resolver }` line anymore. Instead, we insert after the last line in the default `test-helper.js`, the qunit import.
This should support [any version >= 2.17](https://github.com/ember-cli/ember-new-output/blame/v2.17.0/tests/test-helper.js#L3), which hopefully is good enough.
Fixes #262.
> update blueprint to handle newer test-helper.js

- addon/components/flash-message.js
- config/ember-try.js
Ran into this problem on a client project where we needed to add some accessibility fields to these components.
> add aria-label and others to flash message attrs

- .circleci/config.yml
- tests/unit/components/flash-message-test.js
* Updates the circle-ci config to test all scenarios (it was only doing the default and ignoring the `ember-try` configuration).
* Fixes broken test
Closes https://github.com/poteto/ember-cli-flash/issues/278
> fix broken test

- addon/services/flash-messages.js
- addon/utils/flash-message-options.js
- app/initializers/flash-messages.js
- tests/unit/services/flash-messages-test.js
While I was writing a component integration test in my app, I noticed
that I couldn't call `this.flashMessages.success` or any of the built in
convenience functions that target the bootstrap notifications.
This seems to be because, unless an application test runs first, the
service isn't getting set up with the right config. It looks like the
service is expecting it from only the initializer right now.
I changed app/services/flash-message.js to import the config from the
application, so that it is always set up correctly regardless of the
test context.
I also extracted the logic for merging the addon defaults and the app
overrides into a utility module so we could use the same logic in both
places as much as possible.
The unit test was updated to use the flash message service from the app …
> provide default config/overrides to FlashMessageService w/o injections

- addon/utils/flash-message-options.js
This PR avoids deprecation warnings about `Ember.merge` by swapping order in the `||`.
Inspired by https://github.com/simplabs/ember-simple-auth/pull/941/files
Thanks for building this thing!
> Avoid deprecation warning about Ember.merge

- addon/flash/object.js
its fixes #298 
```js
// this works
import { guidFor } from '../utils/computed';
guidFor(whatever);
// and this works
import * as customComputed from '../utils/computed';
customComputed.guidFor(whatever);
// but this does not work.
import customComputed from '../utils/computed';
customComputed.guidFor(whatever);
```
This is a case where ember-cli historically allows a non-spec-compliant behavior.
cc: @Dhaulagiri
> Fix guidFor import

- .circleci/config.yml
- config/ember-try.js
> CHORE: Update node version on CircleCI to 8

- addon/services/flash-messages.js
- addon/utils/computed.js
- tests/unit/services/flash-messages-test.js
fixes #281
Everything open for discussion :)
> feat(service): handle flash object preventDuplicates similar to global option

- addon/components/flash-message.js
- addon/services/flash-messages.js
- addon/utils/get-with-default.js
- tests/unit/utils/get-with-default-test.js
Starting with Ember v3.21, `getWithDefault` is deprecated and will be removed in v4.0.
https://emberjs.github.io/rfcs/0554-deprecate-getwithdefault.html
This PR adds the function as a utility, complete with tests.
I intentionally avoided the nullish operator `??` as it isn't available, based on the project's eslint config.
I did, however, add an explicit check for `null`. [Ember's default implementation does not do this](https://github.com/emberjs/ember.js/blob/93fb76515ec4b808962ea68ae95b11ead6986681/packages/%40ember/-internals/metal/lib/property_get.ts#L180), but it seems appropriate to add given the issues brought up in the RFC and provides a direct upgrade path to using `??` without `get`. I've checked all the usages of `getWithDefault` and believe this change shouldn't cause any …
> Fix `getWithDefault` deprecation warning

- addon/components/flash-message.js
- package.json
- yarn.lock
Instead of using the `@tagName` decorator we can assign the `tagName` property directly, and thus avoid the extra dependency.
Resolves #331
> Remove unnecessary `ember-decorators` dependency

- addon/templates/components/flash-message.hbs
Just noticed this while working on https://github.com/poteto/ember-cli-flash/pull/335
I _think_ `role="alert"` is what we want. There's also `role="alertdialog"` but I think that's more for when there is a decision to be made in a dialog context (eg yes/no/cancel)
> feat: improved a11y for flash message component by default

- CHANGELOG.md
Backfills the changelog to add entries for 1.8.0 - 2.0.0
Fixes https://github.com/poteto/ember-cli-flash/issues/319
> backfill backlog

- README.md
angle bracket syntax for components, and native getters
> update readme to modern standards

- README.md
- addon/components/flash-message.js
- tests/integration/components/flash-message-test.js
Enable the ability to not use the generic bootstrap or foundation class names, by adding ~~`flashTypePrefix`~~`messageStylePrefix` which provides a way for the user to specify the flash type class name prefix.
Backwards compatibility is maintained with `messageStyle`, but if ~~`flashTypePrefix`~~`messageStylePrefix` is set it will take priority.
```hbs
{{#each flashMessages.queue as |flash|}}
<FlashMessage @flash={{this.flash}} @messageStylePrefix="special-alert-" />
{{/each}}
```
would produce an element like
```html
<div class="flash-message special-alert-success" > ... </div>
```
I've been running a custom flash-message component for this addon for a while now, because;
* the flash-message component in this addon was a bit old
* the classes `alert` and `alert-box` are very overused and …
> feat: added messageStylePrefix variable

- README.md
The previous private method mentioned, `_setInitialState`, [was deleted years ago](https://github.com/poteto/ember-cli-flash/commit/8f528df052614349f706090ec38320f97332b741#diff-7849ff4eea465d4b3a6358619e5da44fa1163e0ec092460b8c2694539d417394).
> docs(README): fix text about the tests helper

- addon/components/flash-message.js
- tests/unit/utils/computed-test.js
Importing from `@ember/string` is deprecated as of Ember 3.25
> Update htmlSafe imports

- addon/templates/components/flash-message.hbs
This MR fixes https://github.com/poteto/ember-cli-flash/issues/354
> Fix `this-property-fallback` deprecation warnings

- package.json
To be included in an app, `@ember/render-modifiers` needs to be a dependency of this addon, not just a dev dependency.
Fixes #357.
> Fix missing modifier error in consuming apps

- addon/components/flash-message.js
- addon/templates/components/flash-message.hbs
I'm getting this error in one of my apps:
```
DEPRECATION: `hasBlock` is deprecated. Use `has-block` instead. ('ember-cli-flash/templates/components/flash-message.hbs' @ L9:C8)  [deprecation id: has-block-and-has-block-params] See https://deprecations.emberjs.com/v3.x#toc_has-block-and-has-block-params for more details.
at logDeprecationStackTrace (/Users/peterwagenet/Development/Tilde/events-app/node_modules/ember-source/dist/ember-template-compiler.js:1984:21)
at HANDLERS.<computed> (/Users/peterwagenet/Development/Tilde/events-app/node_modules/ember-source/dist/ember-template-compiler.js:2117:9)
at raiseOnDeprecation (/Users/peterwagenet/Development/Tilde/events-app/node_modules/ember-source/dist/ember-template-compiler.js:2011:9)
at HANDLERS.<computed> …
```
> Change hasBlock to has-block to avoid deprecation

- index.d.ts
- Fixes #381
- [Spec](https://github.com/adopted-ember-addons/ember-cli-flash#arbitrary-options) allows for custom properties to be passed to flash messages
- Isn't possible with the current TS declarations
> Allow arbitrary properties in `MessageOptions` interface

- UPGRADING.md
Correction because I forgot to suggest the removal of the blueprint-generated test helper itself.
[Rendered](https://github.com/adopted-ember-addons/ember-cli-flash/blob/6d8728ef8dbacc7683909e5bf2a4695b5ad0def9/UPGRADING.md)
> Correct test helper blueprint guide

- ember-cli-flash/package.json
Tested the `dist` branch in a local project and noticed that `_app_` files are missing from the packaged output. [Example build](https://github.com/adopted-ember-addons/ember-cli-flash/commit/f4012b7e01da27f88326417a31af47e5960ec1c1)
This causes the addon to break app builds
Can also be reproduced by running `pnpm pack`
**Before**
```
➜  ember-cli-flash git:(master) npm pack
> ember-cli-flash@4.0.0 prepack
> rollup --config
→ dist...
created dist in 541ms
npm notice
npm notice 📦  ember-cli-flash@4.0.0
npm notice === Tarball Contents ===
npm notice 5.9kB  .eslintcache
npm notice 101B   .eslintignore
npm notice 853B   .eslintrc.cjs
npm notice 101B   .prettierignore
npm notice 109B   .prettierrc.cjs
npm notice 63B    .template-lintrc.cjs
npm notice 1.1kB  LICENSE.md
npm notice 20.5kB …
```
> Add missing `files` entry to addon package

- ember-cli-flash/package.json
To allow consumers who are still on `"moduleResolution": "node"` in their TS config (i.e. where TS does not use `exports`) to resolve the types correctly.
> fix(types): add typesVersions map

- ember-cli-flash/src/components/flash-message.js
I don't see why these are still here. They seem to denote all of the tracked properties that are accessed in the getter anyway.
> Remove computed decorators from FlashMessage component
