adopted-ember-addons/ember-cli-flash

- README.md
- addon/services/flash-messages-service.js
- tests/unit/services/flash-messages-service-test.js
Can now add priority to flash messages. Flash messages with higher priority appear at the top of `arrangedQueue`
> Added priority to flash messages

- README.md
- addon/services/flash-messages-service.js
- tests/unit/services/flash-messages-service-test.js
- updated readme
- added tests for type registration
- added ability to register types
- registered defaultTypes on init
- refactored service
Finishes #17
> Add ability to register new types. Finishes #17

- .travis.yml
- circle.yml
- updated travis node version
- https://circleci.com/docs/language-nodejs#node-js-0-12-io-js
> Closes #19. Updated CI node.js to 0.12.x

- .editorconfig
- .npmignore
- bower.json
- package.json
> Updated ember-cli to 0.2.1

- addon/services/flash-messages-service.js
Fix flashMessageDefaults set up.
> Fix flashMessageDefaults set up.

- bower.json
- circle.yml
- index.js
- package.json
- tests/unit/components/flash-message-test.js
Closes #48 
- temporarily bumped up component test timeout, run.later issues to be
addressed in another PR
- be more explicit about global ember-cli version in circle.yml
> Updated ember-cli to 0.2.3

- README.md
Ember CLI updated it's install command.  This commit puts documentation inline with the new command while keeping the old syntax around for those who need it.
> Update README.md for Ember-CLI 0.2.3

- README.md
- blueprints/ember-cli-flash/files/tests/helpers/flash-message.js
- blueprints/ember-cli-flash/index.js
> Added test blueprint

- README.md
- config/ember-try.js
- Also included `1.12.1` into ember-try
Closes #77
> Added note about backwards compatibility.

- .travis.yml
- README.md
- addon/components/flash-message.js
- addon/flash/object.js
- addon/services/flash-messages.js
- addon/utils/computed.js
- config/ember-try.js
- package.json
> Restore ember 1.11.x compatibility

- package.json
> Moved `ember-new-computed` to npm `dependencies` instead.

- blueprints/ember-cli-flash/index.js
> Make jshint pass on test-helper.js

- app/initializers/flash-messages.js
> Fix iteration of wrong array in initializer

- addon/components/flash-message.js
- addon/flash/object.js
- addon/services/flash-messages.js
- app/components/flash-message.js
- app/flash/object.js
- app/services/flash-messages.js
- app/utils/computed.js
- app/utils/object-compact.js
- app/utils/object-only.js
- app/utils/object-without.js
- tests/unit/utils/computed-test.js
- tests/unit/utils/object-compact-test.js
- tests/unit/utils/object-only-test.js
- tests/unit/utils/object-without-test.js
- Minor formatting updates
- Utils are no longer exported into the app, they are for internal use
only
Closes #140
> Fix exports

- .travis.yml
- addon/services/flash-messages.js
- app/initializers/flash-messages.js
- config/ember-try.js
- tests/helpers/module-for-acceptance.js
- tests/helpers/start-app.js
See: http://emberjs.com/blog/2016/04/11/ember-2-5-released.html#toc_code-ember-assign-code
> Fix Ember.merge -> Ember.assign transition and run tests on 2.4 and 2.5

- CONTRIBUTING.md
It appears that recent contributions are no longer following the gitflow branching model.
> Remove obsolete contribution doc

- README.md
Makes the code copy/paste ready
> Add missing parenthesis to test in README

- README.md
Integration tests require a little bit of setup, just like unit tests do.
Fixes #156
> Clarify documentation for integration tests

- CHANGELOG.md
Addresses #151 
This PR adds a simple changelog for some of the previous releases, with the intention of updating with future updates/releases.
> add changelog with release notes

- blueprints/ember-cli-flash/files/tests/helpers/flash-message.js
Please see https://github.com/emberjs/ember.js/issues/14746 for details.
> Remove Usage of Deprecated Ember.K Method

- CHANGELOG.md
- package.json
Version bump to 1.4.1.
cc @poteto Let me know if this looks good and will need you to push to npm 😄
> release v. 1.4.1

- CHANGELOG.md
- package.json
Version bump to fix deprecation warnings
> release 1.5.0

- addon/components/flash-message.js
- tests/integration/components/flash-message-test.js
> add class name integration test

- README.md
Also adds a note that they don't work with sticky messages (which I intend to fix in an followup PR).
> Add a section to readme spelling out how to do animations

- CHANGELOG.md
- package.json
ping @Dhaulagiri or @poteto for v `1.6.3` release
> release v 1.6.3

- README.md
[Here the related issue](https://github.com/poteto/ember-cli-flash/issues/265)
Closes https://github.com/poteto/ember-cli-flash/issues/265
> Update readme to use new modules syntax

- addon/services/flash-messages.js
Fixes #279 (IE11) issue with Object.assign
> Use assign polyfill instead of Object.assign

- README.md
Update unit test docs to reflect new needs requirement
> Documentation update for 1.7.0

- CHANGELOG.md
- package.json
- yarn.lock
Closes https://github.com/poteto/ember-cli-flash/issues/293
> changelog autogeneration

- CONTRIBUTING.md
- README.md
- move contributing instructions away from README.md to CONTRIBUTING.md.
- add a table of contents to README.md
> Readme cleanup + Table of contents

- addon/flash/object.js
> fix: rename flash Object class to FlashObject to avoid transpilation issues

- blueprints/ember-cli-flash/index.js
- package.json
- yarn.lock
> Support ember-cli-version-checker v5 - Fixes #340, #347

- index.d.ts
MessageOptions, FlashFunction and CustomMessageInfo interfaces are useful also when using and customizing the library, this makes sure they are exported as well.
> Export interfaces

- CONTRIBUTING.md
- README.md
- RELEASE.md
Just a little 🧹  self-explanatory.
Please add `documentation`
> Update Contributing and Releasing with `pnpm` and monorepo paths

- ember-cli-flash/package.json
As recommended in [comment thread](https://github.com/adopted-ember-addons/ember-cli-flash/pull/392#pullrequestreview-1691676857) from #392
> Move `@embroider/macros` to peers

- pnpm-lock.yaml
- test-app/package.json
Required to support latest versions of ember-source
> Bump ember-qunit in test-app

- ember-cli-flash/package.json
> Publish files
